// Memory layout of the GPU-resident simulation.
//
// Everything the simulation needs lives in a handful of GPU buffers:
//   ctrl : a few dozen atomic counters + indirect dispatch/draw arguments
//   heap : one big u32 arena holding every work queue and table (free list,
//          dirty lists, impact queue, flood queues, the island-search hash
//          table + union-find, falling-chunk tables, light state, ...)
// The offsets are generated here and injected into the WGSL as constants, so
// TypeScript and the shaders can never disagree about the layout.

export const LIMITS = {
  maxDirty: 65535,
  maxAlloc: 65535,
  maxWrites: 131072,
  maxImpacts: 64,
  maxJobs: 65535,
  maxFlood: 131072,
  maxSeeds: 262144,
  hashSize: 1 << 20,
  maxChunks: 256,
  maxArena: 1 << 20,
  maxLights: 32,
  maxAnchors: 256,
  maxFlashes: 8,
  /** Particles spawned per frame at most (keeps big blasts affordable). */
  spawnBudget: 60000,
  /** Island-search BFS iterations per frame. */
  searchItersPerFrame: 16,
  /** Pane-shatter flood iterations per frame (glass cracks spread across a few frames). */
  floodItersPerFrame: 12,
};

/**
 * Indirect dispatch/draw arguments live in their own buffer: WebGPU forbids a
 * buffer being both the indirect source of a dispatch and writable storage in
 * it, so only the tiny "args" passes bind this one as storage.
 * Dispatch args are 3 words, draw args 4.
 */
const ARGS_NAMES = [
  ['A_IMPACT', 3], ['A_ALLOC', 3], ['A_CARVE', 3], ['A_FLOOD', 3], ['A_SEARCH', 3], ['A_CLEAR', 3],
  ['A_SEEDS', 3], ['A_R0', 3], ['A_RESOLVE', 3], ['A_ARENA', 3], ['A_WRITE', 3], ['A_MAINT', 3],
  ['A_DRAWP', 4], ['A_DRAWC', 4],
] as const;

/** Counters (u32 words) in the ctrl buffer. */
const CTRL_NAMES = [
  ['C_FREE_TOP', 1], ['C_IMPACTS', 1], ['C_JOBS', 1], ['C_ALLOCS', 1], ['C_ALLOC_N', 1],
  ['C_FLOOD_CUR', 1], ['C_FLOOD_NEXT', 1], ['C_FLOOD_PAR', 1],
  ['C_S_STATE', 1], ['C_S_CUR', 1], ['C_S_NEXT', 1], ['C_S_PAR', 1], ['C_NODES', 1], ['C_PENDING', 1],
  ['C_S_ITERS', 1], ['C_SEED_N', 1], ['C_CHUNKS', 1], ['C_ARENA', 1], ['C_WRITES', 1], ['C_WRITE_N', 1],
  ['C_DIRTY', 1], ['C_PCURSOR', 1], ['C_FLASH', 1], ['C_SPAWNED', 1],
  // Stats (read back for the HUD; S_BILL and S_DESTROYED are cleared after each read).
  ['S_BILL', 1], ['S_DESTROYED', 1], ['S_ALLOC_FAIL', 1], ['S_FALLING', 1], ['S_SEARCHES', 1], ['S_ISLANDS', 1],
] as const;

function indexTable<T extends readonly (readonly [string, number])[]>(names: T): { table: Record<T[number][0], number>; words: number } {
  const table = {} as Record<T[number][0], number>;
  let n = 0;
  for (const [name, size] of names) {
    table[name as T[number][0]] = n;
    n += size;
  }
  return { table, words: Math.ceil(n / 4) * 4 };
}

const argsTable = indexTable(ARGS_NAMES);
const ctrlTable = indexTable(CTRL_NAMES);
export const ARGS = argsTable.table;
export const ARGS_WORDS = argsTable.words;
export const CTRL = ctrlTable.table;
export const CTRL_WORDS = ctrlTable.words;

export interface HeapLayout {
  offsets: Record<string, number>;
  words: number;
}

/** Heap sub-arrays (in u32 words). Sizes depend on the world and pool size. */
export function heapLayout(numCells: number, poolCapacity: number, maxParticles: number): HeapLayout {
  const L = LIMITS;
  const parts: [string, number][] = [
    ['FREE_LIST', poolCapacity],
    ['DIRTY_FLAGS', Math.ceil(numCells / 32)],
    ['DIRTY_LIST', L.maxDirty],
    ['ALLOC_FLAGS', Math.ceil(numCells / 32)],
    ['ALLOC_LIST', L.maxAlloc],
    ['WRITE_LIST', L.maxWrites * 2],
    ['IMPACTS', L.maxImpacts * 16],
    ['JOBS', L.maxJobs * 2],
    ['FLOOD_Q', 2 * L.maxFlood * 2],
    ['SEEDS', L.maxSeeds],
    ['HASH_KEYS', L.hashSize],
    ['PARENT', L.hashSize],
    ['NFLAGS', L.hashSize],
    ['NSIZE', L.hashSize],
    ['NODE_LIST', L.hashSize],
    ['SEARCH_Q', 2 * L.hashSize],
    ['CHUNKS', L.maxChunks * 16],
    ['ARENA', L.maxArena * 2],
    ['ALIVE', maxParticles],
    ['LIGHTS', L.maxLights * 16],
    ['ANCHORS', L.maxAnchors * 8],
    ['FLASHES', L.maxFlashes * 8],
    // Final per-frame light list the renderer reads (bound as its own range).
    ['LIGHTS_OUT', (1 + 2 * (L.maxLights + L.maxFlashes)) * 4],
  ];
  const offsets: Record<string, number> = {};
  let o = 0;
  for (const [name, size] of parts) {
    offsets[name] = o;
    // 64 words = 256 bytes: any part can be bound as its own buffer range.
    o += Math.ceil(size / 64) * 64;
  }
  return { offsets, words: o };
}

/** WGSL `const` declarations for the layout + limits. */
export function layoutWGSL(heap: HeapLayout, extra: Record<string, number>): string {
  const lines: string[] = ['// ---- generated by src/gpu/layout.ts ----'];
  for (const [k, v] of Object.entries(ARGS)) lines.push(`const ${k}: u32 = ${v}u;`);
  for (const [k, v] of Object.entries(CTRL)) lines.push(`const ${k}: u32 = ${v}u;`);
  for (const [k, v] of Object.entries(heap.offsets)) lines.push(`const H_${k}: u32 = ${v}u;`);
  const lim: Record<string, number> = {
    MAX_DIRTY: LIMITS.maxDirty,
    MAX_ALLOC: LIMITS.maxAlloc,
    MAX_WRITES: LIMITS.maxWrites,
    MAX_IMPACTS: LIMITS.maxImpacts,
    MAX_JOBS: LIMITS.maxJobs,
    MAX_FLOOD: LIMITS.maxFlood,
    MAX_SEEDS: LIMITS.maxSeeds,
    HASH_SIZE: LIMITS.hashSize,
    MAX_CHUNKS: LIMITS.maxChunks,
    MAX_ARENA: LIMITS.maxArena,
    MAX_LIGHTS: LIMITS.maxLights,
    MAX_ANCHORS: LIMITS.maxAnchors,
    MAX_FLASHES: LIMITS.maxFlashes,
    SPAWN_BUDGET: LIMITS.spawnBudget,
    ...extra,
  };
  for (const [k, v] of Object.entries(lim)) lines.push(`const ${k}: u32 = ${v >>> 0}u;`);
  lines.push('// ---- end generated ----', '');
  return lines.join('\n');
}
